schema_version = "1.0.0"
type = "add-on"
id = "cbb_rf_online_addon"
name = "RF Online importer/exporter"
version = "0.0.1"
tagline = "Importer/exporter for MSH, BN, ANI files, importer only for BSP and R3E."
description = "Importer/exporter for MSH, BN, ANI files, importer only for BSP and R3E."
maintainer = "Cardboard Box"
license = [
  "SPDX:GPL-3.0-or-later",
]
blender_version_min = "4.3.0"
tags = ["Import-Export"]
wheels = [ "./wheels/Wand-0.6.13-py2.py3-none-any.whl", "./wheels/numpy-2.2.3-cp311-cp311-macosx_11_0_arm64.whl", "./wheels/numpy-2.2.3-cp311-cp311-win_amd64.whl", "./wheels/pillow-11.1.0-cp311-cp311-macosx_11_0_arm64.whl", "./wheels/pillow-11.1.0-cp311-cp311-manylinux_2_28_x86_64.whl", "./wheels/pillow-11.1.0-cp311-cp311-win_amd64.whl",]
